# Generated by Django 5.1.4 on 2025-01-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "best_season_to_plant",
                    models.CharField(
                        choices=[
                            ("S1", "Spring"),
                            ("S2", "Summer"),
                            ("S3", "Autumn"),
                            ("S4", "Winter"),
                        ],
                        default="S1",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_date", models.DateField()),
                ("harvest_date", models.DateField(blank=True, null=True)),
                (
                    "fertiliser",
                    models.CharField(
                        choices=[
                            ("TUISF", "Tui Seaweed & Fish Fertiliser"),
                            ("TUICS", "Tui Chicken & Sheep"),
                            ("YATESAP", "Yates Thrive All Purpose Liquid Plant Food"),
                            (
                                "YATESCF",
                                "Yates Thrive Citrus and Fruit Fertiliser Granules",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plant_spot_sunlight_condition",
                    models.CharField(
                        choices=[
                            ("FS", "Full Sun"),
                            ("PS", "Partially Shaded"),
                            ("NS", "No SUN"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "plant_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_calendar.plant",
                    ),
                ),
            ],
        ),
    ]
