# Generated by Django 5.1.4 on 2025-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantcalendar",
            name="plant_spot_sunlight_condition",
            field=models.CharField(
                choices=[
                    ("FS", "Full Sun"),
                    ("PS", "Partially Shaded"),
                    ("NS", "No Sun"),
                ],
                max_length=2,
            ),
        ),
    ]
